enter-chroot from crouton

diff --git a/enter-chroot b/enter-chroot
--- a/enter-chroot
+++ b/enter-chroot
@@ -1,53 +1,159 @@
-#!/bin/sh
+#!/bin/sh -e
+# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
+# Use of this source code is governed by a BSD-style license that can be
+# found in the LICENSE file.
 
-cd /usr/local
+APPLICATION="${0##*/}"
+CHROOTS="`readlink -f "\`dirname "$0"\`/../chroots"`"
+NAME=''
+USERNAME='1000'
+NOLOGIN=''
 
-mount -i -o remount,exec /home/chronos/user
+USAGE="$APPLICATION [options] [command [args...]]
 
-mount -t proc none chroot/proc
-mount -o bind /dev chroot/dev
-mount -o bind /dev/pts chroot/dev/pts
-mount -o bind /sys chroot/sys
-mount -o bind /tmp chroot/tmp
+Enters an installed Debian-based chroot for running alongside Chromium OS.
 
-#mount -o bind /usr/lib64 chroot/usr/local/lib
-#mount -o bind /usr/bin chroot/usr/local/bin
+By default, it will log into the primary user on the first chroot found.
+You can specify a command and parameters to run instead of an interactive shell.
 
-#mount -o bind /usr/lib64/xorg/modules/input chroot/usr/lib/xorg/modules/input
-#mount -o bind /etc/X11/xorg.conf.d chroot/etc/X11/xorg.conf.d
+Options:
+    -c CHROOTS  Directory the chroots are in. Default: $CHROOTS
+    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
+    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
+    -x          Does not log in, but directly executes the command instead.
+                Note that the environment will be empty (sans TERM)."
 
+# Function to exit with exit code $1, spitting out message $@ to stderr
+error() {
+    local ecode="$1"
+    shift
+    echo "$*" 1>&2
+    exit "$ecode"
+}
 
-if [ -f /etc/resolv.conf ]
-then
-	cp /etc/resolv.conf chroot/etc/resolv.conf
+# Process arguments
+while getopts 'c:n:u:x' f; do
+    case "$f" in
+    c) CHROOTS="$OPTARG";;
+    n) NAME="$OPTARG";;
+    u) USERNAME="$OPTARG";;
+    x) NOLOGIN='y';;
+    \?) error 2 "$USAGE";;
+    esac
+done
+shift "$((OPTIND-1))"
+
+# We need to run as root
+if [ ! "$USER" = root -a ! "$UID" = 0 ]; then
+    error 2 "$APPLICATION must be run as root."
 fi
 
-mount -o bind /home/chronos/user/home chroot/home
+# Determine the chroot path
+if [ -n "$NAME" ]; then
+    CHROOT="$CHROOTS/$NAME"
+    if [ ! -d "$CHROOT" ]; then
+        error 1 "$CHROOT not found."
+    fi
+else
+    for CHROOT in "$CHROOTS"/*; do
+        if [ -d "$CHROOT/etc" ]; then
+            NAME="${CHROOT##*/}"
+            break
+        fi
+    done
+    if [ -z "$NAME" ]; then
+        error 1 "No chroots found in $CHROOTS"
+    fi
+fi
 
-case "$1" in
--u)	cp /home/chronos/.Xauthority chroot/home/$2/.Xauthority
-	mount -o bind /home/chronos/user/Downloads chroot/home/$2/Downloads
-	chroot chroot/ /bin/bash -c "cd /home/$2; su $2"
-	umount chroot/home/$2/Downloads
-	;;
--tty)	chroot chroot/ openvt -c $2 -f -w -- /sbin/agetty 38400 tty$2
-	;;
-*)	cp /home/chronos/.Xauthority chroot/root/.Xauthority
-	chroot chroot/ /bin/bash
-	;;
-esac
+# Offer to run /prepare.sh if it exists and yet we're logging in.
+if [ -z "$NOLOGIN" -a -f "$CHROOT/prepare.sh" ]; then
+    echo 'A chroot preparation script still exists inside the chroot.' 1>&2
+    echo 'The chroot may not be fully set up.' 1>&2
+    runprepare='y'
+    if tty -s; then
+        echo -n 'Would you like to finish the setup? [Y/n] ' 1>&2
+        read runprepare
+    fi
+    if [ -z "$runprepare" -o ! "${runprepare#y}" = "$runprepare" ]; then
+        echo 'Preparing chroot environment...' 1>&2
+        "$0" -c "$CHROOTS" -n "$NAME" -x '/prepare.sh'
+        echo 'Setup completed. Entering chroot...' 1>&2
+    else
+        echo 'Skipping setup. You will be prompted again next time.' 1>&2
+    fi
+fi
 
-umount chroot/proc
-umount chroot/dev/pts
-umount chroot/dev
-umount chroot/sys
-umount chroot/tmp
-umount chroot/home
+# Resolve USERNAME if it is a UID (and we're logging in)
+if [ -z "$NOLOGIN" ]; then
+    case "$USERNAME" in
+    ''|*[!0-9]*)
+        # Make sure the username exists
+        if ! grep -q "^$USERNAME:" "$CHROOT/etc/passwd"; then
+            error 1 "User $USERNAME not found in $NAME"
+        fi;;
+     *) 
+        # Resolve the UID
+        uid="$USERNAME"
+        USERNAME="`awk -F: '$3=='"$uid"'{print $1}' "$CHROOT/etc/passwd"`"
+        if [ -z "$USERNAME" ]; then
+            error 1 "UID $uid not found in $NAME"
+        fi
+    esac
+    # Detect the home directory for the user
+    CHROOTHOME="`awk -F: '$1=="'"$USERNAME"'"{print $6}' "$CHROOT/etc/passwd"`"
+fi
 
-#umount chroot/usr/local/lib
-#umount chroot/usr/local/bin
+# Ensure the chroot is executable and writable
+mp="$CHROOT"
+while ! mountpoint -q "$mp"; do
+    mp="${mp%/*}"
+    [ -z "$mp" ] && mp=/
+done
+mount -o remount,rw,dev,exec "$mp"
 
-#umount chroot/usr/lib/xorg/modules/input
-#umount chroot/etc/X11/xorg.conf.d
+# Prepare chroot filesystem
+# Soft-link resolv.conf so that updates are automatically propagated
+mkdir -p "$CHROOT/etc/host-shill"
+ln -sf 'host-shill/resolv.conf' "$CHROOT/etc/resolv.conf"
 
-mount -i -o remount,noexec /home/chronos/user
+# Mounts; will auto-unmount everything below the chroot when the script exits.
+TRAP="sh -e \"`dirname "$0"`/unmount-chroot\" -c \"$CHROOTS\" \"$NAME\";$TRAP"
+trap "$TRAP" INT HUP 0
+mount --bind /dev "$CHROOT/dev"
+mount --bind /dev/pts "$CHROOT/dev/pts"
+mount --bind /dev/shm "$CHROOT/dev/shm"
+mount --bind /sys "$CHROOT/sys"
+mount --bind /sys/fs/fuse/connections "$CHROOT/sys/fs/fuse/connections"
+mount --bind /tmp "$CHROOT/tmp"
+mount --bind /proc "$CHROOT/proc"
+mount --bind /var/run/shill "$CHROOT/etc/host-shill"
+
+# Bind-mount ~/Downloads if we're logged in as a user
+localdownloads='/home/chronos/user/Downloads'
+if [ -z "$NOLOGIN" -a -n "$CHROOTHOME" -a -d "$localdownloads" ]; then
+    mkdir -p "$CHROOT/$CHROOTHOME/Downloads"
+    mount --bind "$localdownloads" "$CHROOT/$CHROOTHOME/Downloads"
+fi
+
+# Disable screen dimming (TODO: create script to poke it instead)
+initctl stop powerd 2>/dev/null || nopowerd=1
+
+# Start the chroot and any specified command
+ret=0
+if [ -n "$NOLOGIN" ]; then
+    env -i TERM="$TERM" chroot "$CHROOT" "$@" || ret=$?
+elif [ $# = 0 ]; then
+    env -i TERM="$TERM" chroot "$CHROOT" su - "$USERNAME" || ret=$?
+else
+    # Escape out the command
+    cmd=''
+    for param in "$@"; do
+        cmd="$cmd\"$param\" "
+    done
+    env -i TERM="$TERM" chroot "$CHROOT" su -c "$cmd" - "$USERNAME" || ret=$?
+fi
+
+# Post-run; clean up
+[ "$nopowerd" ] || initctl start powerd
+exit $ret
